# setup-app.yml

---
  - hosts: webservers
    become: true
    tasks:
      - name: Upload the php file in the webserver
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755 
      
      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=on'
        notify: Restarting the apache

    handlers:  
      - name: Restarting the apache
        service: name=httpd state=restarted
